### ISSUE TITLE
Encoding error

### ISSUE THREAD

**Issue by mschauer** [tkluck/StatProfilerHTML.jl#13]
I get a 
```
This page contains the following errors:

error on line 4214 at column 100: Encoding error
Below is a rendering of the page up to the first error.
```
in `statprof/index.html#`. I attached a zip of the directory if that helps https://www.dropbox.com/s/ssejce8foqexkj2/statprof.zip?dl=0

**Comment by tkluck** [comment]
Is this an error message from your browser? If so, what browser, and is it in the window or the console?

**Comment by mschauer** [comment]
In a red box within the window. Above is Safari. Firefox also errors with a box in the frame below the green title bar.
```
XML Parsing Error: not well-formed
Location: file:///Users/schauermr/.julia/v0.6/Bridge/statprof/clickable_stacks_by_time.svg
Line Number 4214, Column 100:<text text-anchor="" x="179.01" y="315.5" font-size="12" font-family="Verdana" fill="rgb(0,0,0)"  >￿,0)"  ></text>
---------------------------------------------------------------------------------------------------^
```

**Comment by tkluck** [comment]
@mschauer thanks again for reporting this issue, and sorry for not giving it priority sooner. I think it should be fixed now.
