### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by oxinabox** [tkluck/StatProfilerHTML.jl#14]
It seems like  master is a fair bit ahead of the last release

**Comment by tkluck** [comment]
Makes sense to me, thanks for the bump!

@JuliaRegistrator register

**Comment by tkluck** [comment]
Thanks @nkottary for fixing that! Not sure if that means the fixed version has been deployed, but I'll just try:

@JuliaRegistrator register

**Comment by tkluck** [comment]
Credit where credit's due: Also thanks to Frederik Ekre who actually wrote the commit fixing it (but not tagging him as he expressed a wish not to get too many notifications earlier).

**Comment by nkottary** [comment]
No, its not deployed yet. We will deploy it in the next day or two.

**Comment by tkluck** [comment]
Trying again hoping to resolve #15

@JuliaRegistrator register

**Comment by nkottary** [comment]
Hey sorry about this, we're trying to get the fix deployed today.

**Comment by tkluck** [comment]
@nkottary no need to apologize, I appreciate your efforts.

**Comment by nkottary** [comment]
Thanks! This is likely to happen Monday and not today.

**Comment by tkluck** [comment]
@JuliaRegistrator register

**Comment by tkluck** [comment]
@JuliaRegistrator register

**Comment by tkluck** [comment]
Fixed that and waiting for registration at https://github.com/JuliaRegistries/General/pull/3335. Going to close this ticket now. @oxinabox sorry for the delay and @nkottary thanks for solving the deploy issues and making this work!
