### ISSUE TITLE
Customisable output location?

### ISSUE THREAD

**Issue by johnomotani** [tkluck/StatProfilerHTML.jl#26]
It would be nice to be able to (optionally) specify the output directory name that `statprofilehtml()` uses.

Use case: I'm writing an MPI-parallel code. I'd like to be able to write the profile from each process to a separate directory.

**Comment by tkluck** [comment]
Thanks for the suggestion. It was easy to add and the new version 1.3 adds this feature: https://github.com/tkluck/StatProfilerHTML.jl/commit/3af6779d66bac359a70debfede96b134e4699099

**Comment by johnomotani** [comment]
Awesome! Thanks @tkluck!
