### ISSUE TITLE
Not working when JULIA_NUM_THREADS>1

### ISSUE THREAD

**Issue by andreasnoack** [tkluck/StatProfilerHTML.jl#3]
Test pass in the REPL but when I try to run them in IJulia they fail with
<img width="1082" alt="screen shot 2017-10-10 at 11 31 34 am" src="https://user-images.githubusercontent.com/505001/31379523-c0a66f7a-adae-11e7-959b-afba24c645bc.png">

and I have this problem generally when trying to use the package in IJulia.

**Comment by tkluck** [comment]
My sincerest apologies for leaving this issue unanswered for so long! I only notice it now - I suspect something is wrong with my notification settings.

I just installed IJulia in an attempt to reproduce this, but unfortunately, I couldn't: 
![schermafdruk van 2018-01-06 14-59-25](https://user-images.githubusercontent.com/2110529/34640401-50db2e86-f2f2-11e7-8b92-2bf7e1cc4c72.png)

Can you confirm it is still an issue for you? If so, could you share some details about your setup (OS, running jupyter locally or remotely, etc) so I'll have something to go by?

**Comment by andreasnoack** [comment]
Hm. I think this is actually something different. I can't reproduce either but realized that I might have set `JULIA_NUM_THREADS>1` for the IJulia session and indeed I can reproduce the error whenever I use more than a single thread. I've changed the title.

**Comment by tkluck** [comment]
Thanks for the update @andreasnoack . I'll investigate.

**Comment by tkluck** [comment]
I think I found a fix @andreasnoack . I'd be grateful if you could check whether it fixes it for you as well!

**Comment by andreasnoack** [comment]
Indeed. It works now. Thanks for the prompt fix.
