### ISSUE TITLE
Missing perl dependencies on CentOS 7

### ISSUE THREAD

**Issue by VPetukhov** [tkluck/StatProfilerHTML.jl#4]
On julia 0.7 when I get the following error:
```julia
using Profile
using StatProfilerHTML

@profile [rand(1000) for i in 1:10000];
statprofilehtml()
```
> Can't locate autodie.pm in @INC (@INC contains: /home/vp/.julia/packages/StatProfilerHTML/mrcfj/perllib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /home/vp/.julia/packages/StatProfilerHTML/mrcfj/perllib/Devel/StatProfiler/Report.pm line 6.
> BEGIN failed--compilation aborted at /home/vp/.julia/packages/StatProfilerHTML/mrcfj/perllib/Devel/StatProfiler/Report.pm line 6.
> Compilation failed in require at /home/vp/.julia/packages/StatProfilerHTML/mrcfj/bin/statprofilehtml.pl line 13.
> BEGIN failed--compilation aborted at /home/vp/.julia/packages/StatProfilerHTML/mrcfj/bin/statprofilehtml.pl line 13.
> 
> IOError: write: broken pipe (EPIPE)

After I install [autodie](https://metacpan.org/pod/autodie), got the same error for Gzip. I tried to install [PerlIO::gzip](https://metacpan.org/pod/PerlIO::gzip), but it didn't help.

My OS is Centos 7, perl version is 5.16.3. Do you have any suggestions?

**Comment by tkluck** [comment]
Thanks for reporting @VPetukhov . I'm on Ubuntu myself, so I'm currently seeing if I can reproduce this by using the centOS 7 docker image. I'll keep you posted!

**Comment by VPetukhov** [comment]
Thanks! JFYI, I use [this](https://github.com/VPetukhov/linux_configs/blob/master/julia_centos7/Dockerfile) docker.

**Comment by tkluck** [comment]
@VPetukhov it looks like `perl-core` is the RPM package that you need -- I could get it to work by just adding `yum -y install perl-core`. In typical perl distributions, those modules come bundled, as they are part of the same source distribution. CentOS seems to split it off more granularly, which gives the issue that you are seeing.

Could you check that adding that works for you? Then I'll document this in the README and add a more insightful error message.

**Comment by VPetukhov** [comment]
@tkluck Thank you, now it works!
Though I still don't have a graph as in your example, only tables:
![screenshot_20180821_131724](https://user-images.githubusercontent.com/6990194/44398569-a76b8200-a544-11e8-8e77-749e1cf16291.png)

And is it alright that the `statprofilehtml()` command only generate a folder with htmls, but doesn't open anything by itself? It would be really great if you can write couple of sentences on it in the documentation :)

**Comment by tkluck** [comment]
@vpetukhov could you let me know whether that may explain what you're seeing?

**Comment by VPetukhov** [comment]
@tkluck oh, sorry for the delay. And thank you a lot for the answers!

> but are you by any chance using python2 -m SimpleHTTPServer to serve the output?

No, I just use standard Jupyter html viewer.

> As for the missing flamegraph, could you check the output statprof/ directory and see whether it contains the file zoomable_stacks_by_time.svg ?

I don't have time to check it right now, but will give you an update when I'll do.

> Yes, that is correct. If you know of a (cross-platform) way to open a browser window, I'd be happy to add that feature!

Not really, but the quickest solution would be just to print clickable local path to the html file :)

**Comment by VPetukhov** [comment]
Hi,

Sorry for the late reply. I finally reran profiling command, but now it works just fine. I updated a lot of libraries since than, so don't know which one caused problem. Anyway, thank you so much for your help!

**Comment by tkluck** [comment]
You're welcome, and don't hesitate to let me know if you run into any other issues!
