### ISSUE TITLE
Question: What do the colors mean in the flame graph?

### ISSUE THREAD

**Issue by NHDaly** [tkluck/StatProfilerHTML.jl#7]
:D haha i'd been assuming they were just random "fire colors" until someone asked me about it. I can't find any info on the [Devel::StatProfiler](https://github.com/mbarbon/devel-statprofiler) either.

Do you know? :) Thanks!

**Comment by tkluck** [comment]
Ha that's a great question! I'm pretty sure they are indeed just random: if you click the "switch flamegraph" button, they will even switch to different colours. I think the intention is that if one random choice is hard to read, you click that button until it's easier on the eye.

Going to close this issue if you don't mind so I don't worry about the issue count, but don't hesitate to report any other issues here!

**Comment by NHDaly** [comment]
:) Haha thanks, yeah that's what I think too. Just checking to see if you had any insights we were missing. Thanks!
