### ISSUE TITLE
Can we cut a release w/ julia 1.0 support?

### ISSUE THREAD

**Issue by NHDaly** [tkluck/StatProfilerHTML.jl#8]
Right now, you have to install as `StatProfilerHTML#master` because the last Tagged release didn't support `julia 1.0`.

Since it seems to be pretty stable, can we tag a release? Thanks!! :)

**Comment by tkluck** [comment]
Oops! That was an oversight. Just tagged a release but I'm not sure if I got all the details right. Let's see what attobot says. I'll keep this issue open until the release is in the package repository.

**Comment by NHDaly** [comment]
Thaaanks!!! :D

yeah, lgtm!:
https://github.com/JuliaLang/METADATA.jl/pull/20104

**Comment by tkluck** [comment]
Has been merged. Closing this issue. Thanks for your enthusiasm @NHDaly !
